Repository FRONTENDSCHOOL10/5unwan, pull requests merged in 2024-09, with the labels that each got.

#15 Feature: 로그인 페이지 구현, 유저 생성 페이지 구현
  package.json
  pnpm-lock.yaml
  src/api/pocketbase.ts
  src/hooks/user.ts
  src/main.tsx
  src/routes/Home/index.tsx
  src/routes/Login/LoginForm/index.tsx
  src/routes/Login/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/routes/Register/RegisterForm/index.tsx
  src/routes/Register/index.tsx
  src/routes/Start/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#17 Feature: Onboarding(프로필 이미지, 닉네임, 생년월일 등 추가정보 입력) 구현
  src/api/pocketbase.ts
  src/main.tsx
  src/routes/Calendar/index.tsx
  src/routes/Home/index.tsx
  src/routes/Login/index.tsx
  src/routes/Maps/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/OnboardedRoute/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/index.tsx
  src/routes/Onboarding/OnboardingDob/index.tsx
  src/routes/Onboarding/index.tsx
  src/routes/Register/RegisterForm/index.tsx
  src/routes/Register/index.tsx
  src/routes/SharedLayout/index.tsx
  src/routes/SharedLayout/styles.module.css
  src/styles/reset.css
  src/utils/onboarding.tsx
Labels: ✨ Feature, 💄 Style, ♻️ Refactor

#19 Style: CSS변수, fonts설정 및 적용
  src/main.tsx
  src/styles/colors.css
  src/styles/fonts.css
  src/styles/reset.css
  src/styles/styles.css
Labels: 💄 Style

#26 Feat: 운동 기록 모달 창 띄우기
  package.json
  pnpm-lock.yaml
  src/components/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecordModal/index.tsx
  src/components/WorkoutRecordModal/workoutRecordModal.module.css
  src/routes/SharedLayout/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#38 Style: basic styles 변경
  src/styles/colors.css
  src/styles/globals.css
  src/styles/reset.css
Labels: 💄 Style

#36 Feat: input 컴포넌트 제작
  src/components/Input/index.tsx
  src/components/Input/input.module.css
Labels: ✨ Feature, 💄 Style

#41 feat: button 컴포넌트 제작, 로그아웃 기능 구현
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/components/primaryButton/largebutton.module.css
  src/components/primaryButton/largebutton.tsx
  src/components/primaryButton/mediumbutton.module.css
  src/components/primaryButton/mediumbutton.tsx
  src/components/primaryButton/minibutton.module.css
  src/components/primaryButton/minibutton.tsx
  src/components/secondaryButton/largebutton.module.css
  src/components/secondaryButton/largebutton.tsx
  src/components/secondaryButton/mediumbutton.module.css
  src/components/secondaryButton/mediumbutton.tsx
  src/components/secondaryButton/minibutton.module.css
  src/components/secondaryButton/minibutton.tsx
  src/components/tertiaryButton/largebutton.module.css
  src/components/tertiaryButton/largebutton.tsx
  src/components/tertiaryButton/mediumbutton.module.css
  src/components/tertiaryButton/mediumbutton.tsx
  src/components/tertiaryButton/minibutton.module.css
  src/components/tertiaryButton/minibutton.tsx
  src/hooks/user.ts
  src/routes/MyPage/index.tsx
Labels: ✨ Feature, 💄 Style

#52 Refactor: router.tsx에 routes 옮기기
  package.json
  src/components/Spinner/index.tsx
  src/main.tsx
  src/router.tsx
  src/routes/Login/LoginForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/SharedLayout/index.tsx
  src/styles/globals.css
Labels: 🐛 BugFix, ♻️ Refactor

#47 SVG스프라이트, color&font&sapce 스타일 변수 추가
  src/components/SVGicon/index.tsx
  src/components/SVGicon/styles.module.css
  src/components/SVGicon/svgSprites.svg
  src/styles/colors.css
  src/styles/fonts.css
  src/styles/space.css
  src/styles/styles.css
Labels: 💄 Style, 🏚 Markup

#48 Feat: input 컴포넌트 다크모드 추가
  src/components/Input/index.tsx
  src/components/Input/input.module.css
Labels: ✨ Feature, 💄 Style

#58 Refactor: index.html 내용 수정
  index.html
  public/favicon.ico
  public/vite.svg
Labels: ♻️ Refactor

#63 Feat: button 컴포넌트 다크모드 제작
  package-lock.json
  package.json
  src/components/Buttons/IsDarkButton/isdarkButton.module.css
  src/components/Buttons/IsDarkButton/isdarkButton.tsx
  src/components/Buttons/PrimaryButton/largebutton.module.css
  src/components/Buttons/PrimaryButton/largebutton.tsx
  src/components/Buttons/PrimaryButton/mediumbutton.module.css
  src/components/Buttons/PrimaryButton/mediumbutton.tsx
  src/components/Buttons/PrimaryButton/minibutton.module.css
  src/components/Buttons/PrimaryButton/minibutton.tsx
  src/components/Buttons/SecondaryButton/largebutton.module.css
  src/components/Buttons/SecondaryButton/largebutton.tsx
  src/components/Buttons/SecondaryButton/mediumbutton.module.css
  src/components/Buttons/SecondaryButton/mediumbutton.tsx
  src/components/Buttons/SecondaryButton/minibutton.module.css
  src/components/Buttons/SecondaryButton/minibutton.tsx
  src/components/Buttons/TertiaryButton/largebutton.module.css
  src/components/Buttons/TertiaryButton/largebutton.tsx
  src/components/Buttons/TertiaryButton/mediumbutton.module.css
  src/components/Buttons/TertiaryButton/mediumbutton.tsx
  src/components/Buttons/TertiaryButton/minibutton.module.css
  src/components/Buttons/TertiaryButton/minibutton.tsx
  src/routes/MyPage/index.tsx
Labels: ✨ Feature, 💄 Style

#64 Feat: 404 페이지 제작
  index.html
  src/router.tsx
  src/routes/NotFound/index.tsx
  src/routes/NotFound/notFound.module.css
Labels: 💄 Style, 🏚 Markup

#67 Feat: onboarding resume, go home 페이지 구현
  src/api/pocketbase.ts
  src/router.tsx
  src/routes/Login/index.tsx
  src/routes/OnboardedRoute/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/index.tsx
  src/routes/Onboarding/OnboardingDob/index.tsx
  src/routes/Onboarding/OnboardingDone/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/index.tsx
  src/routes/Onboarding/OnboardingInterests/index.tsx
  src/routes/Onboarding/OnboardingResume/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/index.tsx
  src/routes/SharedLayout/index.tsx
Labels: 🐛 BugFix, ✨ Feature, 💄 Style, ♻️ Refactor

#71 Refactor: 404페이지의 button 경로 수정
  src/routes/NotFound/index.tsx
  tsconfig.app.json
Labels: 🐛 BugFix, ♻️ Refactor

#69 Modify: favicon파일 수정
  public/favicon.ico
  public/favicon.svg
Labels: ♻️ Refactor

#72 Feat: isDarkButton 컴포넌트 추가 제작 및 Button 컴포넌트 Link 기능 추가
  src/components/Buttons/IsDarkButton/isDarkButton.tsx
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.tsx
  src/components/Buttons/PrimaryButton/largeButton.module.css
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/PrimaryButton/mediumButton.module.css
  src/components/Buttons/PrimaryButton/mediumButton.tsx
  src/components/Buttons/PrimaryButton/miniButton.module.css
  src/components/Buttons/PrimaryButton/miniButton.tsx
  src/components/Buttons/SecondaryButton/largeButton.module.css
  src/components/Buttons/SecondaryButton/largeButton.tsx
  src/components/Buttons/SecondaryButton/mediumButton.module.css
  src/components/Buttons/SecondaryButton/mediumButton.tsx
  src/components/Buttons/SecondaryButton/miniButton.module.css
  src/components/Buttons/SecondaryButton/miniButton.tsx
  src/components/Buttons/TertiaryButton/largeButton.module.css
  src/components/Buttons/TertiaryButton/largeButton.tsx
  src/components/Buttons/TertiaryButton/mediumButton.module.css
  src/components/Buttons/TertiaryButton/mediumButton.tsx
  src/components/Buttons/TertiaryButton/miniButton.module.css
  src/components/Buttons/TertiaryButton/miniButton.tsx
  src/routes/MyPage/index.tsx
Labels: ✨ Feature, 💄 Style, ♻️ Refactor

#73 Feat: 운동데이터 불러오기
  src/api/pocketbase.ts
  src/routes/Home/index.tsx
Labels: ✨ Feature

#77 Refactor: pb.authStore.onChange 사용하도록 변경
  src/api/pocketbase.ts
  src/hooks/user.ts
  src/routes/MyPage/index.tsx
  src/routes/NotFound/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/routes/SharedLayout/index.tsx
Labels: 🐛 BugFix, ♻️ Refactor

#78 Feat: 회원탈퇴 버튼 제작 및 기능 구현/input 컴포넌트 InputProps 추가/PrimaryButton 컴포넌트 ButtonProps 추가
  src/api/pocketbase.ts
  src/components/Buttons/PrimaryButton/largeButton.module.css
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/PrimaryButton/mediumButton.tsx
  src/components/Buttons/PrimaryButton/miniButton.tsx
  src/components/Input/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/MyPage/myPageModal.module.css
Labels: ✨ Feature, 💄 Style

#79 Refactor: Mypage > import 오류 수정
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/PrimaryButton/miniButton.tsx
  src/routes/MyPage/index.tsx
Labels: ♻️ Refactor

#81 Refactor: React Query 관련 코드 수정
  src/api/pocketbase.ts
  src/hooks/useExercisesQuery.ts
  src/main.tsx
  src/routes/Home/index.tsx
  src/routes/MyPage/index.tsx
Labels: ♻️ Refactor

#75 Markup/home/kim
  package.json
  pnpm-lock.yaml
  src/api/pocketbase.ts
  src/api/pocketbaseWorkouts.ts
  src/components/Article/article.module.css
  src/components/Article/index.tsx
  src/components/Buttons/PrimaryButton/largeButton.module.css
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/PrimaryButton/mediumButton.tsx
  src/components/Buttons/PrimaryButton/miniButton.tsx
  src/components/ExerciseTypes/exerciseTypes.module.css
  src/components/ExerciseTypes/index.tsx
  src/components/Input/index.tsx
  src/components/WorkoutRecordModal/index.tsx
  src/hooks/useExercisesQuery.ts
  src/hooks/useWorkouts.ts
  src/hooks/user.ts
  src/main.tsx
  src/routes/Home/home.module.css
  src/routes/Home/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/MyPage/myPageModal.module.css
  src/routes/NotFound/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/routes/SharedLayout/index.tsx
  src/styles/globals.css
Labels: 💄 Style, 🏚 Markup

#89 Feat: 마이페이지 기본정보/편집모드 구현
  package-lock.json
  src/api/pocketbase.ts
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/SecondaryButton/miniButton.tsx
  src/components/Input/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/MyPage/myPageModal.module.css
Labels: ✨ Feature

#88 Feat: 운동 카테고리 분류
  package-lock.json
  src/api/pocketbase.ts
  src/components/Article/index.tsx
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/SecondaryButton/miniButton.tsx
  src/components/ExerciseTypes/index.tsx
  src/components/Input/index.tsx
  src/routes/Home/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/MyPage/myPageModal.module.css
Labels: ✨ Feature

#95 BugFix: Merge conflicts 시 사라진 코드 복구
  package.json
  pnpm-lock.yaml
  src/api/pocketbase.ts
  src/api/pocketbaseWorkouts.ts
  src/components/Article/index.tsx
  src/components/ExerciseTypes/index.tsx
  src/components/WorkoutRecordModal/index.tsx
  src/hooks/useExercisesQuery.ts
  src/hooks/useWorkouts.ts
  src/main.tsx
  src/routes/Home/index.tsx
Labels: 🐛 BugFix

#96 Refactor: Input 컴포넌트 리팩토링
  src/components/Input/index.tsx
Labels: ♻️ Refactor

#92 Feat: Home 유저프로필
  src/routes/Home/UserInfo/index.tsx
  src/routes/Home/UserInfo/user.module.css
  src/routes/Home/home.module.css
  src/routes/Home/index.tsx
Labels: 💄 Style, 🏚 Markup

#102 Feat: 로그아웃 페이지 구현 및 스타일링 / 회원 탈퇴 페이지 구현 및 스타일링
  package-lock.json
  package.json
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/PrimaryButton/miniButton.tsx
  src/components/Buttons/TertiaryButton/miniButton.tsx
  src/router.tsx
  src/routes/MyPage/DeleteAccount/deleteAccount.module.css
  src/routes/MyPage/DeleteAccount/deleteAccount.tsx
  src/routes/MyPage/DeleteAccount/deleteComplete.module.css
  src/routes/MyPage/DeleteAccount/deleteComplete.tsx
  src/routes/MyPage/LogoutComplete/index.tsx
  src/routes/MyPage/LogoutComplete/logoutComplete.module.css
  src/routes/MyPage/index.tsx
  src/routes/MyPage/myPageModal.module.css
Labels: ✨ Feature, 💄 Style

#103 Revert "Feat: Home 유저프로필"
  src/routes/Home/UserInfo/index.tsx
  src/routes/Home/UserInfo/user.module.css
  src/routes/Home/home.module.css
  src/routes/Home/index.tsx
Labels: 🐛 BugFix, ♻️ Refactor

#105 Refactor: 누락된 UserInfo 컴포넌트
  src/routes/Home/UserInfo/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/Home/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#106 Remove: 레포지토리로부터 env파일 삭제
  .env
  .gitignore
Labels: 🔥 Remove

#114 BugFix: #77 지워진 PR 복구
  src/api/pocketbase.ts
  src/hooks/user.ts
  src/routes/MyPage/DeleteAccount/deleteAccount.tsx
  src/routes/MyPage/index.tsx
  src/routes/NotFound/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/routes/SharedLayout/index.tsx
Labels: 🐛 BugFix, ♻️ Refactor

#116 Feat: 캘린더에 운동기록 불러오기, eslint 이슈 수정
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/api/pocketbase.ts
  src/hooks/useWorkouts.ts
  src/routes/Calendar/index.tsx
  src/routes/Onboarding/OnboardingBasic/index.tsx
  src/routes/Onboarding/OnboardingDob/index.tsx
  src/routes/Onboarding/OnboardingHeight/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/index.tsx
  src/routes/Onboarding/OnboardingWeight/index.tsx
  src/routes/SharedLayout/index.tsx
  src/styles/styles.css
  src/utils/onboarding.tsx
Labels: 🐛 BugFix, ⚙ Settings, ✨ Feature, ♻️ Refactor

#108 Refactor: Input 컴포넌트
  src/components/Input/index.tsx
  src/components/Input/input.module.css
  src/routes/Maps/index.tsx
Labels: ♻️ Refactor

#111 Refactor: index.html
  index.html
  public/favicon.png
Labels: ♻️ Refactor

#117 Refactor: button 컴포넌트 수정
  package-lock.json
  src/components/Buttons/PrimaryButton/button.module.css
  src/components/Buttons/PrimaryButton/index.tsx
  src/components/Buttons/PrimaryButton/largeButton.module.css
  src/components/Buttons/PrimaryButton/largeButton.tsx
  src/components/Buttons/PrimaryButton/mediumButton.module.css
  src/components/Buttons/PrimaryButton/mediumButton.tsx
  src/components/Buttons/PrimaryButton/miniButton.module.css
  src/components/Buttons/PrimaryButton/miniButton.tsx
  src/components/Buttons/SecondaryButton/button.module.css
  src/components/Buttons/SecondaryButton/index.tsx
  src/components/Buttons/SecondaryButton/largeButton.module.css
  src/components/Buttons/SecondaryButton/largeButton.tsx
  src/components/Buttons/SecondaryButton/mediumButton.module.css
  src/components/Buttons/SecondaryButton/mediumButton.tsx
  src/components/Buttons/SecondaryButton/miniButton.module.css
  src/components/Buttons/SecondaryButton/miniButton.tsx
  src/components/Buttons/TertiaryButton/button.module.css
  src/components/Buttons/TertiaryButton/index.tsx
  src/components/Buttons/TertiaryButton/largeButton.module.css
  src/components/Buttons/TertiaryButton/largeButton.tsx
  src/components/Buttons/TertiaryButton/mediumButton.module.css
  src/components/Buttons/TertiaryButton/mediumButton.tsx
  src/components/Buttons/TertiaryButton/miniButton.module.css
  src/components/Buttons/TertiaryButton/miniButton.tsx
  src/routes/MyPage/DeleteAccount/deleteAccount.module.css
  src/routes/MyPage/DeleteAccount/deleteAccount.tsx
  src/routes/MyPage/DeleteAccount/deleteComplete.module.css
  src/routes/MyPage/DeleteAccount/deleteComplete.tsx
  src/routes/MyPage/LogoutComplete/index.tsx
  src/routes/MyPage/LogoutComplete/logoutComplete.module.css
  src/routes/MyPage/index.module.css
  src/routes/MyPage/index.tsx
  src/routes/NotFound/index.tsx
Labels: ♻️ Refactor

#119 Feat: useId, lazy 추가
  src/router.tsx
  src/routes/Login/LoginForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/index.tsx
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/index.tsx
  src/routes/Onboarding/OnboardingDob/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/index.tsx
  src/routes/Register/RegisterForm/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#122 Refactor: Input 컴포넌트 수정
  src/components/Input/index.tsx
  src/components/Input/input.module.css
  src/routes/Maps/MapBoard/mapBoard.module.css
Labels: ♻️ Refactor

#123 Feat: 카카오지도API 연동(기본틀)
  index.html
  src/router.tsx
  src/routes/Maps/MapBoard/index.tsx
  src/routes/Maps/SearchForm/index.tsx
  src/routes/Maps/SearchForm/searchForm.module.css
  src/routes/Maps/index.tsx
  src/routes/Maps/map.module.css
Labels: ✨ Feature

#126 Refactor: Input 컴포넌트
  src/components/Input/index.tsx
  src/components/Input/input.module.css
  src/routes/Maps/MapBoard/index.tsx
Labels: ♻️ Refactor

#133 Feat: Calendar 페이지 구현 및 small changes
  src/api/pocketbaseWorkouts.ts
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/routes/Calendar/calendar.module.css
  src/routes/Calendar/index.tsx
  src/routes/NotFound/notFound.module.css
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🏚 Markup, ♻️ Refactor

#135 Feat: 다크모드 기능 구현
  src/components/DarkModeContext/DarkModeContext.tsx
  src/components/DarkModeToggleButton/DarkModeToggleButton.tsx
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecord/WorkoutRecordForm/workoutRecordModal.module.css
  src/main.tsx
  src/routes/Home/UserInfo/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/MyPage/index.tsx
  src/styles/reset.css
Labels: ✨ Feature, 💄 Style, 🔥 Remove, ♻️ Refactor, 🚀 Test

#132 Feat: zustand 설치 및 Maps컴포넌트 적용
  package.json
  pnpm-lock.yaml
  src/routes/Maps/MapBoard/index.tsx
  src/routes/Maps/SearchForm/index.tsx
  src/routes/Maps/SearchList/index.tsx
  src/routes/Maps/index.tsx
  src/stores/mapStore.tsx
Labels: ⚙ Settings, ✨ Feature

#140 Style: 운동기록 모달 다크모드 적용
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.tsx
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecord/WorkoutRecordForm/workoutRecordModal.module.css
  src/components/WorkoutRecord/WorkoutRecordModal/index.tsx
  src/components/WorkoutRecord/WorkoutRecordModal/workoutRecordModal.module.css
Labels: ✨ Feature, 💄 Style, 🏚 Markup, ♻️ Refactor

#146 Style: GNB 다크모드 적용
  src/components/SVGicon/styles.module.css
  src/routes/SharedLayout/index.tsx
  src/routes/SharedLayout/styles.module.css
Labels: ✨ Feature, 💄 Style

#143 Refactor: Home컴포넌트
  src/routes/Home/Article/article.module.css
  src/routes/Home/Article/index.tsx
  src/routes/Home/ExerciseTypes/exerciseTypes.module.css
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/index.tsx
  src/stores/homeStore.tsx
Labels: ♻️ Refactor

#147 Modify: NotFountPage 수정
  src/routes/NotFound/index.tsx
  src/routes/NotFound/notFound.module.css
Labels: ♻️ Refactor

#149 Feat: Home 컴포넌트 프로필
  src/routes/Home/UserInfo/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/Home/index.tsx
Labels: ✨ Feature

#151 Feature: 헤더 컴포넌트 제작 및 적용
  src/components/Header/header.module.css
  src/components/Header/index.tsx
  src/components/SVGicon/index.tsx
  src/router.tsx
  src/routes/Login/index.tsx
  src/routes/Maps/SearchForm/searchForm.module.css
  src/routes/Maps/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/Onboarding/index.tsx
  src/routes/Register/index.tsx
  src/routes/SharedLayout/index.tsx
  src/routes/SharedLayout/styles.module.css
Labels: ✨ Feature, 💄 Style, 🏚 Markup, ♻️ Refactor

#154 Style: main 컴포넌트 스타일링
  src/components/SVGicon/index.tsx
  src/components/SVGicon/svgSprites.svg
  src/routes/Start/index.tsx
  src/routes/Start/start.module.css
Labels: 💄 Style

#156 Refactor: Input컴포넌트 수정
  src/components/Input/index.tsx
  src/components/Input/input.module.css
  src/routes/Maps/SearchForm/index.tsx
Labels: ♻️ Refactor

#162 modify: Input컴포넌트 수정
  src/components/Input/index.tsx
  src/components/Input/input.module.css
Labels: ♻️ Refactor

#163 Style: 버튼 width 및 margin 수정
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.module.css
  src/components/Buttons/PrimaryButton/button.module.css
  src/components/Buttons/SecondaryButton/button.module.css
  src/components/Buttons/TertiaryButton/button.module.css
Labels: 💄 Style

#164 Style: 마이페이지 스타일링
  package-lock.json
  package.json
  src/api/pocketbase.ts
  src/components/Input/index.tsx
  src/routes/MyPage/InterestModal/index.tsx
  src/routes/MyPage/InterestModal/modal.module.css
  src/routes/MyPage/index.module.css
  src/routes/MyPage/index.tsx
Labels: 💄 Style

#165 Refactor: SearchForm 컴포넌트
  src/routes/Maps/SearchForm/index.tsx
Labels: ♻️ Refactor

#166 Style: Start, Login 페이지, LoginForm컴포넌트
  .cSpell.json
  src/components/Input/index.tsx
  src/components/KakaoLogin/index.tsx
  src/components/KakaoLogin/kakaoLogin.module.css
  src/routes/Login/LoginForm/index.tsx
  src/routes/Login/LoginForm/loginForm.module.css
  src/routes/Login/index.tsx
  src/routes/Login/login.module.css
  src/routes/Maps/SearchForm/index.tsx
  src/routes/Start/index.tsx
  src/routes/Start/start.module.css
Labels: ✨ Feature, 💄 Style, 🏚 Markup

#171 Style: 회원가입 페이지 스타일링 및 컴포넌트 일부 수정
  pnpm-lock.yaml
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.tsx
  src/components/Buttons/PrimaryButton/index.tsx
  src/components/Buttons/SecondaryButton/index.tsx
  src/components/Buttons/TertiaryButton/index.tsx
  src/components/Input/index.tsx
  src/components/PageTitle/index.tsx
  src/components/PageTitle/style.module.css
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/style.module.css
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/index.tsx
  src/routes/Onboarding/OnboardingDob/OnboardingDobForm/style.module.css
  src/routes/Onboarding/OnboardingDone/index.tsx
  src/routes/Onboarding/OnboardingDone/style.module.css
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/index.tsx
  src/routes/Onboarding/OnboardingHeight/OnboardingHeightForm/style.module.css
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/style.module.css
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/index.tsx
  src/routes/Onboarding/OnboardingWeight/OnboardingWeightForm/style.module.css
  src/routes/Onboarding/index.tsx
  src/routes/Onboarding/style.module.css
  src/routes/Register/RegisterForm/index.tsx
  src/routes/Register/RegisterForm/style.module.css
  src/routes/Register/index.tsx
  src/routes/Register/style.module.css
Labels: 💄 Style, 🏚 Markup, ♻️ Refactor

#178 Feat: 즐겨찾기 기능 구현
  src/routes/Maps/SearchList/index.tsx
  src/stores/mapStore.tsx
Labels: ✨ Feature

#180 Feat: home 페이지 type 기능추가
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/index.tsx
  src/routes/SharedLayout/index.tsx
Labels: ✨ Feature

#186 Style: 로그인 페이지 스타일링
  src/components/KakaoLogin/kakaoLogin.module.css
  src/routes/Login/LoginForm/loginForm.module.css
  src/routes/Login/index.tsx
  src/routes/Login/login.module.css
Labels: 💄 Style, 🏚 Markup

#190 Refactor: map 페이지
  package.json
  pnpm-lock.yaml
  src/routes/Maps/MapBoard/index.tsx
  src/routes/Maps/MapBoard/mapBoard.module.css
  src/routes/Maps/SearchForm/index.tsx
  src/routes/Maps/SearchList/index.tsx
  src/routes/Maps/SearchList/searchList.module.css
  src/routes/Maps/index.tsx
  src/stores/mapStore.tsx
Labels: ✨ Feature, ♻️ Refactor

#193 Feat: 가입 시 관심종목 1개로 제한
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/style.module.css
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/index.tsx
  src/routes/Onboarding/OnboardingInterests/OnboardingInterestsForm/style.module.css
Labels: ✨ Feature, 💄 Style, 🏚 Markup

#195 Feat: small changes
  src/components/WorkoutRecord/WorkoutRecordModal/index.tsx
  src/routes/Calendar/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#198 Feature/registerlogin/yun
  src/components/PageTitle/index.tsx
  src/routes/DeleteAccount/deleteAccount.module.css
  src/routes/DeleteAccount/index.tsx
  src/routes/LogoutComplete/index.tsx
  src/routes/LogoutComplete/logoutComplete.module.css
Labels: 💄 Style, 🏚 Markup

#200 Style: 다크모드 토글 스타일링 및 페이지적용
  src/components/DarkModeToggleButton/DarkModeToggleButton.tsx
  src/components/DarkModeToggleButton/style.module.css
  src/routes/MyPage/index.tsx
Labels: 💄 Style, 🏚 Markup

#201 Refactor: 홈, 지도페이지 확인
  .cSpell.json
  src/routes/Home/Article/article.module.css
  src/routes/Home/Article/index.tsx
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/UserInfo/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/Home/home.module.css
  src/routes/Home/index.tsx
  src/routes/Maps/MapBoard/index.tsx
  src/routes/Maps/MapBoard/mapBoard.module.css
  src/routes/Maps/SearchForm/index.tsx
  src/routes/Maps/SearchForm/searchForm.module.css
  src/routes/Maps/SearchList/index.tsx
  src/routes/Maps/SearchList/searchList.module.css
  src/routes/Maps/SearchTypes/index.tsx
  src/routes/Maps/SearchTypes/searchTypes.module.css
  src/routes/Maps/index.tsx
  src/stores/homeStore.tsx
  src/stores/mapStore.tsx
Labels: ✨ Feature, 💄 Style, ♻️ Refactor

#202 Feat: Spinner에 포탈 설정
  index.html
  src/components/SpinnerPortal/index.tsx
  src/routes/Calendar/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/routes/SharedLayout/index.tsx
Labels: ✨ Feature, ♻️ Refactor

#191 Feat: 관심운동 수정 기능
  package-lock.json
  src/api/pocketbase.ts
  src/routes/DeleteAccount/index.tsx
  src/routes/MyPage/InterestModal/index.tsx
  src/routes/MyPage/InterestModal/modal.module.css
  src/routes/MyPage/index.module.css
  src/routes/MyPage/index.tsx
Labels: ✨ Feature, 💄 Style, ♻️ Refactor

#204 Style: 다크모드 토글 포커스
  src/components/DarkModeToggleButton/DarkModeToggleButton.tsx
Labels: 💄 Style

#210 Style: 다크모드 적용
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.tsx
  src/components/Buttons/PrimaryButton/button.module.css
  src/components/Buttons/SecondaryButton/button.module.css
  src/components/Buttons/TertiaryButton/button.module.css
  src/components/DarkModeContext/DarkModeContext.tsx
  src/components/DarkModeToggleButton/style.module.css
  src/components/Input/index.tsx
  src/components/PageTitle/index.tsx
  src/components/PageTitle/style.module.css
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecord/WorkoutRecordModal/index.tsx
  src/routes/Calendar/calendar.module.css
  src/routes/Calendar/index.tsx
  src/routes/Home/Article/article.module.css
  src/routes/Home/Article/index.tsx
  src/routes/Home/ExerciseTypes/exerciseTypes.module.css
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/Home/index.tsx
  src/routes/MyPage/InterestModal/index.tsx
  src/routes/MyPage/InterestModal/modal.module.css
  src/routes/MyPage/index.module.css
  src/routes/MyPage/index.tsx
  src/styles/space.css
Labels: 🐛 BugFix, 💄 Style, 🏚 Markup

#211 Modify: 전체적인 코드 수정
  index.html
  netlify.toml
  public/favicon.webp
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.tsx
  src/components/Buttons/PrimaryButton/button.module.css
  src/components/Buttons/SecondaryButton/button.module.css
  src/components/Buttons/TertiaryButton/button.module.css
  src/components/DarkModeContext/DarkModeContext.tsx
  src/components/DarkModeToggleButton/style.module.css
  src/components/Input/index.tsx
  src/components/KakaoLogin/index.tsx
  src/components/KakaoLogin/kakaoLogin.module.css
  src/components/PageTitle/index.tsx
  src/components/PageTitle/style.module.css
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecord/WorkoutRecordModal/index.tsx
  src/routes/Calendar/calendar.module.css
  src/routes/Calendar/index.tsx
  src/routes/Home/Article/article.module.css
  src/routes/Home/Article/index.tsx
  src/routes/Home/ExerciseTypes/exerciseTypes.module.css
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/Home/index.tsx
  src/routes/MyPage/InterestModal/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/style.module.css
  src/routes/Onboarding/OnboardingDone/index.tsx
  src/routes/Onboarding/OnboardingInterests/style.module.css
  src/routes/Onboarding/OnboardingResume/index.tsx
  src/routes/Onboarding/OnboardingResume/onBoardingResume.module.css
  src/routes/Register/index.tsx
  src/routes/SharedLayout/index.tsx
  src/routes/Start/index.tsx
  src/routes/Start/start.module.css
  src/styles/reset.css
  src/styles/space.css
Labels: ♻️ Refactor

#214 BugFix: revert PR #211
  index.html
  netlify.toml
  public/favicon.webp
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkPrimaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.module.css
  src/components/Buttons/IsDarkButton/isDarkSecondaryButton.tsx
  src/components/Buttons/IsDarkButton/isDarkTertiaryButton.tsx
  src/components/Buttons/PrimaryButton/button.module.css
  src/components/Buttons/SecondaryButton/button.module.css
  src/components/Buttons/TertiaryButton/button.module.css
  src/components/DarkModeContext/DarkModeContext.tsx
  src/components/DarkModeToggleButton/style.module.css
  src/components/Input/index.tsx
  src/components/KakaoLogin/index.tsx
  src/components/KakaoLogin/kakaoLogin.module.css
  src/components/PageTitle/index.tsx
  src/components/PageTitle/style.module.css
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecord/WorkoutRecordModal/index.tsx
  src/routes/Calendar/calendar.module.css
  src/routes/Calendar/index.tsx
  src/routes/Home/Article/article.module.css
  src/routes/Home/Article/index.tsx
  src/routes/Home/ExerciseTypes/exerciseTypes.module.css
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/Home/index.tsx
  src/routes/MyPage/InterestModal/index.tsx
  src/routes/MyPage/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/style.module.css
  src/routes/Onboarding/OnboardingDone/index.tsx
  src/routes/Onboarding/OnboardingInterests/style.module.css
  src/routes/Onboarding/OnboardingResume/index.tsx
  src/routes/Onboarding/OnboardingResume/onBoardingResume.module.css
  src/routes/Register/index.tsx
  src/routes/SharedLayout/index.tsx
  src/routes/Start/index.tsx
  src/routes/Start/start.module.css
  src/styles/reset.css
  src/styles/space.css
Labels: 🐛 BugFix

#212 Style: map 페이지 스타일링
  src/components/SVGicon/index.tsx
  src/components/SVGicon/svgSprites.svg
  src/routes/Maps/MapBoard/index.tsx
  src/routes/Maps/MapBoard/mapBoard.module.css
  src/routes/Maps/SearchForm/searchForm.module.css
  src/routes/Maps/SearchList/index.tsx
  src/routes/Maps/SearchList/searchList.module.css
Labels: 💄 Style, 🏚 Markup, ♻️ Refactor

#215 Docs: README.md 작성(1)
  README.md
Labels: 📃 Docs

#217 Refactor: 전체적인 수정
  index.html
  public/favicon.webp
  src/components/KakaoLogin/index.tsx
  src/components/KakaoLogin/kakaoLogin.module.css
  src/routes/Home/ExerciseTypes/index.tsx
  src/routes/Home/UserInfo/userInfo.module.css
  src/routes/MyPage/InterestModal/index.tsx
  src/routes/MyPage/InterestModal/modal.module.css
  src/routes/MyPage/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingDone/index.tsx
  src/routes/Onboarding/OnboardingInterests/style.module.css
  src/routes/Onboarding/OnboardingResume/index.tsx
  src/routes/Onboarding/OnboardingResume/onBoardingResume.module.css
  src/routes/Register/index.tsx
  src/routes/SharedLayout/index.tsx
  src/routes/Start/index.tsx
  src/routes/Start/start.module.css
  src/styles/reset.css
Labels: ♻️ Refactor

#219 Feature: 일부 페이지 스타일 수정
  src/components/Header/header.module.css
  src/components/WorkoutRecord/WorkoutRecordForm/index.tsx
  src/components/WorkoutRecord/WorkoutRecordForm/workoutRecordModal.module.css
  src/components/WorkoutRecord/WorkoutRecordModal/index.tsx
  src/components/WorkoutRecord/WorkoutRecordModal/workoutRecordModal.module.css
  src/routes/Calendar/calendar.module.css
  src/routes/Calendar/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/index.tsx
  src/routes/Onboarding/OnboardingBasic/OnboardingBasicForm/style.module.css
  src/styles/colors.css
Labels: ✨ Feature, 💄 Style, 🏚 Markup, ♻️ Refactor

#222 Bugfix: map 버그 수정
  index.html
  src/routes/Maps/SearchList/index.tsx
  src/routes/Maps/SearchList/searchList.module.css
Labels: 🐛 BugFix

#226 Feat: 마이페이지 프로필 사진 업로드 활성화
  src/routes/MyPage/index.module.css
  src/routes/MyPage/index.tsx
Labels: 🐛 BugFix, ✨ Feature, 💄 Style, 🏚 Markup
