Repository FRONTENDSCHOOL10/5unwan, pull requests merged in 2024-08, with the labels that each got.

#2 🎉 Settings: init 설정
  .gitignore
  .npmrc
  eslint.config.js
  index.html
  jsconfig.json
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.jsx
  src/main.jsx
  src/styles/globals.css
  vite.config.js
Labels: ⚙ Setting

#5 Docs: README.md 내용추가
  README.md
Labels: 📃 Docs

#7 Docs: PR 템플릿 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#12 Feat: Kakao 로그인 연동
  .env
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/api/pocketbase.ts
  src/components/Spinner/index.tsx
  src/components/Spinner/styles.module.css
  src/main.tsx
  src/routes/Home/index.tsx
  src/routes/Login/index.tsx
  src/routes/PrivateRoute/index.tsx
  src/vite-env.d.ts
Labels: 🐛 BugFix, ⚙ Settings, ✨ Feature
